# Generated by Django 4.2.7 on 2023-12-04 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_tourcategory_bookingtour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingtour',
            old_name='due_date',
            new_name='booking_date',
        ),
    ]
